// SPDX-FileCopyrightText: 2026 Uwe Jugel
// SPDX-License-Identifier: AGPL-3.0-or-later

package loom

import "strings"

// Render draws root into an off-screen canvas of the given size and returns each
// row as an ANSI string (styles reset at every row end, matching Canvas.Row). It
// opens no terminal, so it is safe in headless contexts, tests, and screenshots.
func Render(root Widget, cols, rows int) []string {
	c := NewCanvas(cols, rows)
	root.Draw(c, c.Bounds())
	out := make([]string, rows)
	for y := 0; y < rows; y++ {
		out[y] = c.Row(y)
	}
	return out
}

// ScreenshotScript turns rendered ANSI rows into a minimal, self-printing POSIX
// shell script: running it replays the captured frame with its original colors.
// Each row is emitted as a single-quoted argument to one printf, with ESC bytes
// written as \033 and embedded single quotes escaped, so the file stays plain
// 7-bit text with no raw control characters. The comment is placed in a header
// line (newlines collapsed) to identify the shot.
func ScreenshotScript(rows []string, comment string) string {
	var b strings.Builder
	b.WriteString("#!/usr/bin/env bash\n")
	if comment != "" {
		b.WriteString("# ")
		b.WriteString(strings.ReplaceAll(comment, "\n", " "))
		b.WriteByte('\n')
	}
	b.WriteString("# generated by loom — re-run this file to reprint the frame\n")
	b.WriteString("printf '%b\\n'")
	for _, row := range rows {
		b.WriteString(" \\\n  '")
		b.WriteString(shellEscapeRow(row))
		b.WriteByte('\'')
	}
	b.WriteByte('\n')
	return b.String()
}

// shellEscapeRow makes one ANSI row safe inside printf '%b' single quotes:
// raw ESC (0x1b) becomes the \033 octal escape that %b re-expands, and any
// single quote is closed-escaped-reopened ('\”).
func shellEscapeRow(row string) string {
	row = strings.ReplaceAll(row, "\x1b", "\\033")
	row = strings.ReplaceAll(row, "'", "'\\''")
	return row
}
